/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 25-дек-2021 19:30:27 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `user` CASCADE
;

/* Create Tables */

CREATE TABLE `user`
(
	`u_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`u_name` VARCHAR(200) NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`u_id` ASC)
)

;

SET FOREIGN_KEY_CHECKS=1
; 
