/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 26-дек-2021 0:49:46 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `computer` CASCADE
;

DROP TABLE IF EXISTS `emplyee_1_M_identifying` CASCADE
;

DROP TABLE IF EXISTS `m2m_student_subject` CASCADE
;

DROP TABLE IF EXISTS `passport` CASCADE
;

DROP TABLE IF EXISTS `passport2` CASCADE
;

DROP TABLE IF EXISTS `passport2` CASCADE
;

DROP TABLE IF EXISTS `payment` CASCADE
;

DROP TABLE IF EXISTS `person_1_1_with_pFK` CASCADE
;

DROP TABLE IF EXISTS `person_1_1_with_unique_FK` CASCADE
;

DROP TABLE IF EXISTS `romm_1_M_not_identifying` CASCADE
;

DROP TABLE IF EXISTS `student_M_M` CASCADE
;

DROP TABLE IF EXISTS `subject` CASCADE
;

/* Create Tables */

CREATE TABLE `computer`
(
	`c_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`c_room` INT UNSIGNED NULL,
	`p_description` VARCHAR(200) NOT NULL,
	CONSTRAINT `PK_computer` PRIMARY KEY (`c_id` ASC)
)

;

CREATE TABLE `emplyee_1_M_identifying`
(
	`e_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`e_passport` CHAR(9) NULL,
	`e_name` VARCHAR(50) NULL,
	CONSTRAINT `PK_emplyee_1_M` PRIMARY KEY (`e_id` ASC)
)

;

CREATE TABLE `m2m_student_subject`
(
	`st_id` INT UNSIGNED NOT NULL,
	`sb_id` INT UNSIGNED NOT NULL,
	`mark` INT NULL,
	CONSTRAINT `PK_m2m_student_subject` PRIMARY KEY (`st_id` ASC, `sb_id` ASC)
)

;

CREATE TABLE `passport`
(
	`pt_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pt_number` CHAR(9) NULL,
	CONSTRAINT `PK_passport` PRIMARY KEY (`pt_id` ASC)
)

;

CREATE TABLE `passport2`
(
	`pt_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pt_number` CHAR(9) NULL,
	`pt_owner` INT UNSIGNED NULL,
	CONSTRAINT `PK_passport2` PRIMARY KEY (`pt_id` ASC)
)

;

CREATE TABLE `passport2`
(
	`pt_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pt_number` CHAR(9) NULL,
	CONSTRAINT `PK_passport` PRIMARY KEY (`pt_id` ASC)
)

;

CREATE TABLE `payment`
(
	`p_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`p_person` INT UNSIGNED NOT NULL,
	`p_money` DECIMAL(10,2) NOT NULL,
	CONSTRAINT `PK_payment` PRIMARY KEY (`p_id` ASC, `p_person` ASC)
)

;

CREATE TABLE `person_1_1_with_pFK`
(
	`pn_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pn_name` VARCHAR(200) NULL,
	CONSTRAINT `PK_person_1_1_with_pFK` PRIMARY KEY (`pn_id` ASC)
)

;

CREATE TABLE `person_1_1_with_unique_FK`
(
	`pn_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`pn_name` VARCHAR(200) NULL,
	CONSTRAINT `PK_person_1_1_with_pFK` PRIMARY KEY (`pn_id` ASC)
)

;

CREATE TABLE `romm_1_M_not_identifying`
(
	`r_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`r_name` VARCHAR(200) NULL,
	CONSTRAINT `PK_romm_1_m_not_identifying` PRIMARY KEY (`r_id` ASC)
)

;

CREATE TABLE `student_M_M`
(
	`st_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`st_name` VARCHAR(200) NULL,
	CONSTRAINT `PK_student_M_M` PRIMARY KEY (`st_id` ASC)
)

;

CREATE TABLE `subject`
(
	`sb_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`sb_name` VARCHAR(200) NULL,
	CONSTRAINT `PK_subject` PRIMARY KEY (`sb_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `computer` 
 ADD INDEX `IXFK_computer_romm_1_M_not_identifying` (`c_room` ASC)
;

ALTER TABLE `emplyee_1_M_identifying` 
 ADD CONSTRAINT `UNQ_passport` UNIQUE (`e_passport` ASC)
;

ALTER TABLE `m2m_student_subject` 
 ADD INDEX `IXFK_m2m_student_subject_student_M_M` (`st_id` ASC)
;

ALTER TABLE `m2m_student_subject` 
 ADD INDEX `IXFK_m2m_student_subject_subject` (`sb_id` ASC)
;

ALTER TABLE `passport` 
 ADD INDEX `IXFK_passport_person_1_1_with_pFK` (`pt_id` ASC)
;

ALTER TABLE `passport2` 
 ADD CONSTRAINT `UNQ_owner` UNIQUE (`pt_owner` ASC)
;

ALTER TABLE `passport2` 
 ADD INDEX `IXFK_passport2_person_1_1_with_unique_FK` (`pt_owner` ASC)
;

ALTER TABLE `passport2` 
 ADD INDEX `IXFK_passport_person_1_1_with_pFK` (`pt_id` ASC)
;

ALTER TABLE `payment` 
 ADD INDEX `IXFK_payment_emplyee_1_M_identifying` (`p_person` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `computer` 
 ADD CONSTRAINT `FK_computer_romm_1_M_not_identifying`
	FOREIGN KEY (`c_room`) REFERENCES `romm_1_M_not_identifying` (`r_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `m2m_student_subject` 
 ADD CONSTRAINT `FK_m2m_student_subject_student_M_M`
	FOREIGN KEY (`st_id`) REFERENCES `student_M_M` (`st_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `m2m_student_subject` 
 ADD CONSTRAINT `FK_m2m_student_subject_subject`
	FOREIGN KEY (`sb_id`) REFERENCES `subject` (`sb_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `passport` 
 ADD CONSTRAINT `FK_passport_person_1_1_with_pFK`
	FOREIGN KEY (`pt_id`) REFERENCES `person_1_1_with_pFK` (`pn_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `passport2` 
 ADD CONSTRAINT `FK_passport2_person_1_1_with_unique_FK`
	FOREIGN KEY (`pt_owner`) REFERENCES `person_1_1_with_unique_FK` (`pn_id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `passport2` 
 ADD CONSTRAINT `FK_passport_person_1_1_with_pFK`
	FOREIGN KEY (`pt_id`) REFERENCES  () ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `payment` 
 ADD CONSTRAINT `FK_payment_emplyee_1_M_identifying`
	FOREIGN KEY (`p_person`) REFERENCES `emplyee_1_M_identifying` (`e_id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
